### ISSUE TITLE
暂时没有资源可供作图哦，可以稍后再来！

### ISSUE THREAD

**Issue by purelolly** [EtherLeaF/nonebot-plugin-colab-novelai#10]
![8FO%K8@ZP72M(@N~OKR{8XU](https://user-images.githubusercontent.com/78009999/212731358-f483521a-9396-486c-a770-12a15eb47be3.png)

**Comment by thetapilla** [comment]
**你的控制台日志呢？？**

<img src=https://user-images.githubusercontent.com/100039483/212810172-70d7523a-c0d8-4c05-818d-bf605f5d7ac9.jpg width=40% />

**Comment by TomorrowLost** [comment]
![E@D(O8A%HA~SHCLZ S@@$Z2](https://user-images.githubusercontent.com/78009999/212876857-43f18580-2763-4ee2-a85a-c079683ffbd1.png)
![E2_2![E@D(O8A%HA~SHCLZ S@@$Z2](https://user-images.githubusercontent.com/78009999/212876857-43f18580-2763-4ee2-a85a-c079683ffbd1.png)
ZYZ0WT3SGU5~@C~}A](https://user-images.githubusercontent.com/78009999/212876866-63f11e29-0515-422a-a74f-1f8850976817.png)
01-17 18:25:09 [ERROR] nonebot | Failed to import "nonebot_plugin_colab_novelai"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/nonebot2/MIbot/./bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_colab_novelai/__init__.py", line 16, in <module>
    from .utils import chrome_driver, inject_image_to_state
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_colab_novelai/utils/__init__.py", line 1, in <module>
    from .webdriver import (
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/nonebot_plugin_colab_novelai/utils/webdriver.py", line 43, in <module>
    chrome_driver = webdriver.Chrome(service=Service(driver_path), options=options)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/root/anaconda3/envs/nonebot2/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: unable to connect to renderer
  (failed to check if window was closed: disconnected: unable to connect to renderer)
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
#0 0x5647eda962a3 <unknown>
#1 0x5647ed854f77 <unknown>
#2 0x5647ed83c29b <unknown>
#3 0x5647ed82eadc <unknown>
#4 0x5647ed82e805 <unknown>
#5 0x5647ed8ba20f <unknown>
#6 0x5647ed8b9a5f <unknown>
#7 0x5647ed8b1903 <unknown>
#8 0x5647ed884ece <unknown>
#9 0x5647ed885fde <unknown>
#10 0x5647edae663e <unknown>
#11 0x5647edae9b79 <unknown>
#12 0x5647edacc89e <unknown>
#13 0x5647edaeaa83 <unknown>
#14 0x5647edabf505 <unknown>
#15 0x5647edb0bca8 <unknown>
#16 0x5647edb0be36 <unknown>
#17 0x5647edb27333 <unknown>
#18 0x7fe03f9eaea5 start_thread

**Comment by purelolly** [comment]
![J1$7$UI6T@BFNM_CJB4M)M2](https://user-images.githubusercontent.com/78009999/212890287-01a11782-d465-43d6-b1cb-59ee3e104292.png)
![Uploading )O~ZEX(PC4UO5QR33(CDD8S.png…]()

**Comment by purelolly** [comment]
![8BI{`2}89{$C1)H X54LWFY](https://user-images.githubusercontent.com/78009999/212896358-3ba687a2-a6d5-4917-960f-6f6f07bfc084.png)
![CP42Y0HLIY{F%`KFZLB1}O](https://user-images.githubusercontent.com/78009999/212896365-1abd2c36-ca42-47dd-a6a5-1614509a357e.png)
![Q)}@MRI~(@UD F%30X}L5PF](https://user-images.githubusercontent.com/78009999/212896374-4cfe5190-18a7-4c96-b681-10fc838c17a7.png)

**Comment by purelolly** [comment]
![8BI{`2}89{$C1)H X54LWFY](https://user-images.githubusercontent.com/78009999/212896424-5d6db2d9-e8af-4c89-a6a8-e753b96e636d.png)

**Comment by purelolly** [comment]
百度了，安装也是出错 没卵用
