### ISSUE TITLE
运行插件保存：unsupported operand type(s) for |: '_GenericAlias' and 'type'

### ISSUE THREAD

**Issue by xi-yue-233** [EtherLeaF/nonebot-plugin-colab-novelai#4]
> 11-20 01:42:27 [ERROR] nonebot | Failed to import "nonebot_plugin_colab_novelai"
Traceback (most recent call last):
  File "E:\qqbot-nonebot\Nonebot\nb2\bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "D:\python-software\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\python-software\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\python-software\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "D:\python-software\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\python-software\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "D:\python-software\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\python-software\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\__init__.py", line 16, in <module>
    from .utils import chrome_driver, inject_image_to_state
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\utils\__init__.py", line 1, in <module>
    from .webdriver import (
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\utils\webdriver.py", line 14, in <module>
    from .distributed import PLUGIN_DIR
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\utils\distributed.py", line 13, in <module>
    from ..config import plugin_config
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\config.py", line 7, in <module>
    class Config(BaseModel, extra=Extra.ignore):
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\config.py", line 22, in Config
    nai_nsfw_tags: Optional[List[str] | str] = None
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'type'

![image](https://user-images.githubusercontent.com/58218656/202864346-b12f766e-09c3-43cd-bc4a-3e3b76468692.png)

**Comment by thetapilla** [comment]
Python版本的问题 下个更新会修复
