### ISSUE TITLE
可否使用clash代理进行colab访问？

### ISSUE THREAD

**Issue by xi-yue-233** [EtherLeaF/nonebot-plugin-colab-novelai#5]
手上没有可以访问外网的服务器，本地测试时候只能使用代理

**Comment by thetapilla** [comment]
不是很推荐走clash。
之后的版本会加一个类似于```colab_proxy=xxx```的配置项

**Comment by thetapilla** [comment]
插件[v0.2.2](https://pypi.org/project/nonebot-plugin-colab-novelai/0.2.2/)已更新

**Comment by simpleYOTO** [comment]
大佬我想问一下代理IP怎么弄TAT

**Comment by simpleYOTO** [comment]
大佬，IP我弄好了，机器人回复没有资源可供作图是因为太多人使用了吗

**Comment by xi-yue-233** [comment]
我把clash配置好之后显示的是没有资源可供做图，控制台报错
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54883): Max retries exceeded with url: /session/8bd3b703546838a0901a2c8d2c1c8083/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ED8D07A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

`Traceback (most recent call last):
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\python-software\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\python-software\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\python-software\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\python-software\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\python-software\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "D:\python-software\lib\http\client.py", line 948, in send
    self.connect()
  File "D:\python-software\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "D:\python-software\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020ED8D07370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\qqbot-nonebot\Nonebot\nb2\bot.py", line 39, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "D:\python-software\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\python-software\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "D:\python-software\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "D:\python-software\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\python-software\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python-software\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\python-software\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\python-software\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\python-software\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\python-software\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\python-software\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\_main.py", line 129, in access_colab_with_accounts
    await run_colab(gmail, password, cpolar_authtoken)
  File "D:\python-software\lib\site-packages\asyncer\_main.py", line 358, in wrapper
    return await anyio.to_thread.run_sync(
  File "D:\python-software\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\python-software\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\python-software\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\access\colab.py", line 99, in run_colab
    force_refresh_webpage(driver, NOTEBOOK_URL)
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\utils\webdriver.py", line 63, in force_refresh_webpage
    driver.get(url)
  File "D:\python-software\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in get
    self.execute(Command.GET, {"url": url})
  File "D:\python-software\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 442, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\python-software\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 294, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\python-software\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 316, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "D:\python-software\lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
  File "D:\python-software\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "D:\python-software\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\python-software\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54883): Max retries exceeded with url: /session/8bd3b703546838a0901a2c8d2c1c8083/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ED8D07370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
11-29 00:33:33 [WARNING] apscheduler | Execution of job "asyncify.<locals>.wrapper (trigger: interval[0:00:10], next run at: 2022-11-29 00:33:33 CST)" skipped: maximum number of running instances reached (1)
11-29 00:33:39 [ERROR] apscheduler | Job "asyncify.<locals>.wrapper (trigger: interval[0:00:10], next run at: 2022-11-29 00:33:43 CST)" raised an exception
Traceback (most recent call last):
  File "D:\python-software\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\python-software\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\python-software\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\python-software\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\python-software\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\python-software\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\python-software\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\python-software\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "D:\python-software\lib\http\client.py", line 948, in send
    self.connect()
  File "D:\python-software\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "D:\python-software\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020ED8D07A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\qqbot-nonebot\Nonebot\nb2\bot.py", line 39, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "D:\python-software\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\python-software\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "D:\python-software\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "D:\python-software\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\python-software\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python-software\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\python-software\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\python-software\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\python-software\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\python-software\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\python-software\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\python-software\lib\site-packages\asyncer\_main.py", line 358, in wrapper
    return await anyio.to_thread.run_sync(
  File "D:\python-software\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\python-software\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\python-software\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\_main.py", line 39, in handle_recaptcha
    driver.switch_to.frame(driver.find_element(By.XPATH, '/html/body/colab-recaptcha-dialog/div/div/iframe'))
  File "D:\python-software\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "D:\python-software\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 442, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\python-software\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 294, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\python-software\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 316, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "D:\python-software\lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
  File "D:\python-software\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "D:\python-software\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\python-software\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54883): Max retries exceeded with url: /session/8bd3b703546838a0901a2c8d2c1c8083/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ED8D07A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))`

**Comment by thetapilla** [comment]
> 大佬，IP我弄好了，机器人回复没有资源可供作图是因为太多人使用了吗

检查你的日志，看看账号有没有连上

**Comment by thetapilla** [comment]
> 我把clash配置好之后显示的是没有资源可供做图，控制台报错 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54883): Max retries exceeded with url: /session/8bd3b703546838a0901a2c8d2c1c8083/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ED8D07A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
> 
> `Traceback (most recent call last): File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request conn.request(method, url, **httplib_request_kw) File "D:\python-software\lib\site-packages\urllib3\connection.py", line 239, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "D:\python-software\lib\http\client.py", line 1253, in request self._send_request(method, url, body, headers, encode_chunked) File "D:\python-software\lib\http\client.py", line 1299, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "D:\python-software\lib\http\client.py", line 1248, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "D:\python-software\lib\http\client.py", line 1008, in _send_output self.send(msg) File "D:\python-software\lib\http\client.py", line 948, in send self.connect() File "D:\python-software\lib\site-packages\urllib3\connection.py", line 205, in connect conn = self._new_conn() File "D:\python-software\lib\site-packages\urllib3\connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020ED8D07370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "E:\qqbot-nonebot\Nonebot\nb2\bot.py", line 39, in nonebot.run(app="**mp_main**:app", access_log=False) File "D:\python-software\lib\site-packages\nonebot__init__.py", line 273, in run get_driver().run(*args, **kwargs) File "D:\python-software\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run uvicorn.run( File "D:\python-software\lib\site-packages\uvicorn\main.py", line 576, in run server.run() File "D:\python-software\lib\site-packages\uvicorn\server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "D:\python-software\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "D:\python-software\lib\asyncio\base_events.py", line 629, in run_until_complete self.run_forever() File "D:\python-software\lib\asyncio\windows_events.py", line 316, in run_forever super().run_forever() File "D:\python-software\lib\asyncio\base_events.py", line 596, in run_forever self._run_once() File "D:\python-software\lib\asyncio\base_events.py", line 1890, in _run_once handle._run() File "D:\python-software\lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args)
> 
> > File "D:\python-software\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
> > retval = await job.func(*job.args, **job.kwargs)
> > File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai_main.py", line 129, in access_colab_with_accounts
> > await run_colab(gmail, password, cpolar_authtoken)
> > File "D:\python-software\lib\site-packages\asyncer_main.py", line 358, in wrapper
> > return await anyio.to_thread.run_sync(
> > File "D:\python-software\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
> > return await get_asynclib().run_sync_in_worker_thread(
> > File "D:\python-software\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread
> > return await future
> > File "D:\python-software\lib\site-packages\anyio_backends_asyncio.py", line 867, in run
> > result = context.run(func, *args)
> > File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\access\colab.py", line 99, in run_colab
> > force_refresh_webpage(driver, NOTEBOOK_URL)
> > File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai\utils\webdriver.py", line 63, in force_refresh_webpage
> > driver.get(url)
> > File "D:\python-software\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in get
> > self.execute(Command.GET, {"url": url})
> > File "D:\python-software\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 442, in execute
> > response = self.command_executor.execute(driver_command, params)
> > File "D:\python-software\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 294, in execute
> > return self._request(command_info[0], url, body=data)
> > File "D:\python-software\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 316, in _request
> > response = self._conn.request(method, url, body=body, headers=headers)
> > File "D:\python-software\lib\site-packages\urllib3\request.py", line 78, in request
> > return self.request_encode_body(
> > File "D:\python-software\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
> > return self.urlopen(method, url, **extra_kw)
> > File "D:\python-software\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
> > response = conn.urlopen(method, u.request_uri, **kw)
> > File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
> > return self.urlopen(
> > File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
> > return self.urlopen(
> > File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
> > return self.urlopen(
> > File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
> > retries = retries.increment(
> > File "D:\python-software\lib\site-packages\urllib3\util\retry.py", line 592, in increment
> > raise MaxRetryError(_pool, url, error or ResponseError(cause))
> > urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54883): Max retries exceeded with url: /session/8bd3b703546838a0901a2c8d2c1c8083/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ED8D07370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
> > 11-29 00:33:33 [WARNING] apscheduler | Execution of job "asyncify..wrapper (trigger: interval[0:00:10], next run at: 2022-11-29 00:33:33 CST)" skipped: maximum number of running instances reached (1)
> > 11-29 00:33:39 [ERROR] apscheduler | Job "asyncify..wrapper (trigger: interval[0:00:10], next run at: 2022-11-29 00:33:43 CST)" raised an exception
> > Traceback (most recent call last):
> > File "D:\python-software\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
> > conn = connection.create_connection(
> > File "D:\python-software\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
> > raise err
> > File "D:\python-software\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
> > sock.connect(sa)
> > ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request conn.request(method, url, **httplib_request_kw) File "D:\python-software\lib\site-packages\urllib3\connection.py", line 239, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "D:\python-software\lib\http\client.py", line 1253, in request self._send_request(method, url, body, headers, encode_chunked) File "D:\python-software\lib\http\client.py", line 1299, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "D:\python-software\lib\http\client.py", line 1248, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "D:\python-software\lib\http\client.py", line 1008, in _send_output self.send(msg) File "D:\python-software\lib\http\client.py", line 948, in send self.connect() File "D:\python-software\lib\site-packages\urllib3\connection.py", line 205, in connect conn = self._new_conn() File "D:\python-software\lib\site-packages\urllib3\connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020ED8D07A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "E:\qqbot-nonebot\Nonebot\nb2\bot.py", line 39, in nonebot.run(app="**mp_main**:app", access_log=False) File "D:\python-software\lib\site-packages\nonebot__init__.py", line 273, in run get_driver().run(*args, **kwargs) File "D:\python-software\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run uvicorn.run( File "D:\python-software\lib\site-packages\uvicorn\main.py", line 576, in run server.run() File "D:\python-software\lib\site-packages\uvicorn\server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "D:\python-software\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "D:\python-software\lib\asyncio\base_events.py", line 629, in run_until_complete self.run_forever() File "D:\python-software\lib\asyncio\windows_events.py", line 316, in run_forever super().run_forever() File "D:\python-software\lib\asyncio\base_events.py", line 596, in run_forever self._run_once() File "D:\python-software\lib\asyncio\base_events.py", line 1890, in _run_once handle._run() File "D:\python-software\lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args)
> 
> > File "D:\python-software\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
> > retval = await job.func(*job.args, **job.kwargs)
> > File "D:\python-software\lib\site-packages\asyncer_main.py", line 358, in wrapper
> > return await anyio.to_thread.run_sync(
> > File "D:\python-software\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
> > return await get_asynclib().run_sync_in_worker_thread(
> > File "D:\python-software\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread
> > return await future
> > File "D:\python-software\lib\site-packages\anyio_backends_asyncio.py", line 867, in run
> > result = context.run(func, *args)
> > File "D:\python-software\lib\site-packages\nonebot_plugin_colab_novelai_main.py", line 39, in handle_recaptcha
> > driver.switch_to.frame(driver.find_element(By.XPATH, '/html/body/colab-recaptcha-dialog/div/div/iframe'))
> > File "D:\python-software\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
> > return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
> > File "D:\python-software\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 442, in execute
> > response = self.command_executor.execute(driver_command, params)
> > File "D:\python-software\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 294, in execute
> > return self._request(command_info[0], url, body=data)
> > File "D:\python-software\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 316, in _request
> > response = self._conn.request(method, url, body=body, headers=headers)
> > File "D:\python-software\lib\site-packages\urllib3\request.py", line 78, in request
> > return self.request_encode_body(
> > File "D:\python-software\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
> > return self.urlopen(method, url, **extra_kw)
> > File "D:\python-software\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
> > response = conn.urlopen(method, u.request_uri, **kw)
> > File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
> > return self.urlopen(
> > File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
> > return self.urlopen(
> > File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
> > return self.urlopen(
> > File "D:\python-software\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
> > retries = retries.increment(
> > File "D:\python-software\lib\site-packages\urllib3\util\retry.py", line 592, in increment
> > raise MaxRetryError(_pool, url, error or ResponseError(cause))
> > urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54883): Max retries exceeded with url: /session/8bd3b703546838a0901a2c8d2c1c8083/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ED8D07A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))`

这是刚开始启动就连不上。你代理的端口是54883吗

**Comment by xi-yue-233** [comment]
代理端口是7890
.env里面是这样配置的
![L@ MC @ ~9%~XE %T{65RM](https://user-images.githubusercontent.com/58218656/204831300-7c78eb51-6b8c-464d-8e09-214bb3278d5d.png)

**Comment by thetapilla** [comment]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/100039483/205446545-3cc83fbe-be23-478c-978b-2c699b76f8f0.png">
测试了下没啥问题，，这个就不清楚了
